/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2024-01-02 08:30:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.about;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/style.css\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/630c352365.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/main.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      out.write("\r\n");
      out.write("	<section id=\"about_container\">\r\n");
      out.write("	\r\n");
      out.write("		<div id =\"about\">\r\n");
      out.write("			<h1>ABOUT US</h1>\r\n");
      out.write("			\r\n");
      out.write("			<div id=\"about_introduction\">\r\n");
      out.write("				<img src=\"../resources/images/logo.png\">\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<h2>PRODUCED BY</h2>\r\n");
      out.write("			<div id=\"people\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<img src=\"../resources/images/예은.png\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<span>임예은 Project Leader</span>\r\n");
      out.write("						<p>\r\n");
      out.write("						<br>\r\n");
      out.write("						프로젝트 일정 관리 및 여정담 디자인 총괄 디렉터\r\n");
      out.write("						국내 / 해외 메인 페이지 제작 (HTML, CSS)\r\n");
      out.write("						숙소 & 교통 페이지 제작 (HTML, CSS)\r\n");
      out.write("						발표자료 (PPT) 제작 및 발표자\r\n");
      out.write("\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div><img src=\"../resources/images/상현.png\">\r\n");
      out.write("					<div>\r\n");
      out.write("					<span>이상현 Team member</span>\r\n");
      out.write("					<p>\r\n");
      out.write("					<br>\r\n");
      out.write("					코드 병합 진행 및 DB 총괄 디렉터\r\n");
      out.write("					최종 결과물 서버 연결 및 구축\r\n");
      out.write("					커뮤니티 DB 작업 진행 (여행후기, 나의 계획 등)\r\n");
      out.write("					하위 카테고리 페이지 제작 (HTML, CSS, DB\r\n");
      out.write("					</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<img src=\"../resources/images/가은.png\">\r\n");
      out.write("					<div>\r\n");
      out.write("					<span>이가은 Team member</span>\r\n");
      out.write("					<p>\r\n");
      out.write("					<br>\r\n");
      out.write("					코드 병합 진행 및 여정담 디자인 제작 참여  \r\n");
      out.write("					여정담 메인 페이지 제작 (HTML, CSS)\r\n");
      out.write("					ABOUT 페이지 제작 (HTML, CSS)\r\n");
      out.write("					로그인, 회원가입 페이지 제작 (HTML, CSS, DB)\r\n");
      out.write("\r\n");
      out.write("					</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<img src=\"../resources/images/지훈.png\">\r\n");
      out.write("					<div>\r\n");
      out.write("					<span>서지훈 Team member</span>\r\n");
      out.write("					<p>\r\n");
      out.write("					<br>\r\n");
      out.write("					주제 선정 배경 조사 및 개발환경 및 도구 정리  \r\n");
      out.write("					커뮤니티 HTML, CSS 작업 진행\r\n");
      out.write("					멤버쉽 페이지 제작 (HTML, CSS)\r\n");
      out.write("					자주하는 질문 페이지 제작 (HTML, CSS)\r\n");
      out.write("\r\n");
      out.write("					</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<img src=\"../resources/images/채희.png\">\r\n");
      out.write("					<div>\r\n");
      out.write("					<span>박채희 Team member</span>\r\n");
      out.write("					<p>\r\n");
      out.write("					<br>\r\n");
      out.write("					코드 병합 진행 및 여정담 디자인 제작 참여\r\n");
      out.write("					마이페이지 제작 (HTML, CSS, DB)\r\n");
      out.write("					찜 목록 페이지 제작 (HTML, CSS, DB)\r\n");
      out.write("					프로필 수정 페이지 제작 (HTML, CSS, DB)\r\n");
      out.write("\r\n");
      out.write("					</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<img src=\"../resources/images/나경.png\">\r\n");
      out.write("					<div>\r\n");
      out.write("					<span>이나경 Team member</span>\r\n");
      out.write("					<p>\r\n");
      out.write("					<br>\r\n");
      out.write("					여정담 디자인 및 발표자료 (PPT) 제작 참여\r\n");
      out.write("					팀 정기 회의록 작성 및 역할 분담표 제작\r\n");
      out.write("					국내 / 해외 상세 페이지 제작 (HTML, CSS)\r\n");
      out.write("					각 국가, 지역별 내용 정리 및 추가 페이지 제작\r\n");
      out.write("					</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("	</section>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
