/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2024-01-02 08:30:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.travel;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class in_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>국내 여행 | 메인</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/in_main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/style.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/aa24b12773.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- header -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<section id=\"main_container\">\r\n");
      out.write("	    <!-- body 부분 -->\r\n");
      out.write("	    <section>\r\n");
      out.write("	      <!-- 국가/도시 검색 창 영역 -->\r\n");
      out.write("	      <div id=\"mainPicture\">\r\n");
      out.write("	        <img src=\"images/jeju-winter.jpg\" alt=\"메인 화면\">\r\n");
      out.write("	        <div class=\"searchTravel\">\r\n");
      out.write("	          <p>어디로 여행가시나요?</p>\r\n");
      out.write("	          <div class=\"searchWord\">\r\n");
      out.write("	            <label>\r\n");
      out.write("	              <input type=\"text\" placeholder=\" 국가명, 도시명으로 검색하세요. (추천 도시 : 홍콩, 뉴욕, 제주도)\" size=\"65%\">\r\n");
      out.write("	              <button type=\"button\"><i class=\"fa-solid fa-magnifying-glass fa-lg\" style=\"color: #606060;\"></i></button>\r\n");
      out.write("	            </label>\r\n");
      out.write("	          </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("  \r\n");
      out.write("	      <!-- 대한민국 도시 선택 창 영역 -->\r\n");
      out.write("	      <div id=\"searchCity\">\r\n");
      out.write("	        <div class=\"searchCityBox\">\r\n");
      out.write("	          <p>국내 여행지</p>\r\n");
      out.write("	          <table>\r\n");
      out.write("	            <tbody>\r\n");
      out.write("	              <!-- 첫번째 행 -->\r\n");
      out.write("	              <tr>\r\n");
      out.write("	                <td>주요 도시</td>\r\n");
      out.write("	                <td>서울</td>\r\n");
      out.write("	                <td>제주</td>\r\n");
      out.write("	                <td>강릉</td>\r\n");
      out.write("	                <td>부산</td>\r\n");
      out.write("	                <td>포항</td>\r\n");
      out.write("	                <td>춘천</td>\r\n");
      out.write("	                <td>속초</td>\r\n");
      out.write("	              </tr>\r\n");
      out.write("	              \r\n");
      out.write("	              <!-- 두번째 행 -->\r\n");
      out.write("	              <tr>\r\n");
      out.write("	                <!-- 강원도 -->\r\n");
      out.write("	                <td>\r\n");
      out.write("	                  <div class=\"dropdown\">\r\n");
      out.write("	                    <button id=\"dropbtn\" class=\"dropbtn\">\r\n");
      out.write("	                      <span class=\"dropbtn_content\"><p>강원도</p></span>\r\n");
      out.write("	                      <span class=\"dropbtn_click\" style=\"font-family: Material Icons; font-size : 20px; color : #707070; float:right;\"\r\n");
      out.write("	                        onclick=\"dropdown()\">arrow_drop_down</span>\r\n");
      out.write("	                    </button>\r\n");
      out.write("	                    <div class=\"dropdown-content\">\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city\">원주</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city\">춘천</div></a>\r\n");
      out.write("	                      <a href=\"http://localhost:8080/travel/gangneung.jsp\"><div class=\"city\">강릉</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city\">동해</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city\">속초</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city\">삼척</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city\">태백</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city\">홍천</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city\">철원</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city\">횡성</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city\">평창</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city\">정선</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city\">영월</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city\">인제</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city\">고성</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city\">양양</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city\">화천</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city\">양구</div></a>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                  </div>\r\n");
      out.write("	                </td>\r\n");
      out.write("	\r\n");
      out.write("	                <!-- 경기도 -->\r\n");
      out.write("	                <td>\r\n");
      out.write("	                  <div class=\"dropdown\">\r\n");
      out.write("	                    <button id=\"dropbtn2\" class=\"dropbtn\">\r\n");
      out.write("	                      <span id=\"dropbtn_content2\" class=\"dropbtn_content\"><p>경기도</p></span>\r\n");
      out.write("	                      <span class=\"dropbtn_click\" style=\"font-family: Material Icons; font-size : 20px; color : #707070; float:right;\"\r\n");
      out.write("	                        onclick=\"dropdown2()\">arrow_drop_down</span>\r\n");
      out.write("	                    </button>\r\n");
      out.write("	                    <div id=\"dropdown-content2\" class=\"dropdown-content\">\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">수원</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">용인</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">고양</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">성남</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">화성</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">부천</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">남양주</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">안산</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">평택</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">안양</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">시흥</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">파주</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">김포</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">의정부</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">광주</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">하남</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">광명</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">군포</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">양주</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">오산</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">이천</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">안산</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">구리</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">의왕</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">포천</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">여주</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">과천</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">양평</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">가평</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">연천</div></a>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                  </div>\r\n");
      out.write("	                </td>\r\n");
      out.write("	\r\n");
      out.write("	                <!-- 서울 -->\r\n");
      out.write("	                <td>서울</td>\r\n");
      out.write("	\r\n");
      out.write("	                <!-- 인천 -->\r\n");
      out.write("	                <td>인천</td>\r\n");
      out.write("	\r\n");
      out.write("	                <!-- 대전 -->\r\n");
      out.write("	                <td>대전</td>\r\n");
      out.write("	\r\n");
      out.write("	                <!-- 충청남도 -->\r\n");
      out.write("	                <td>\r\n");
      out.write("	                  <div class=\"dropdown\">\r\n");
      out.write("	                    <button id=\"dropbtn3\" class=\"dropbtn\">\r\n");
      out.write("	                      <span id=\"dropbtn_content3\" class=\"dropbtn_content\"><p>충청남도</p></span>\r\n");
      out.write("	                      <span class=\"dropbtn_click\" style=\"font-family: Material Icons; font-size : 20px; color : #707070; float:right;\"\r\n");
      out.write("	                        onclick=\"dropdown3()\">arrow_drop_down</span>\r\n");
      out.write("	                    </button>\r\n");
      out.write("	                    <div id=\"dropdown-content3\" class=\"dropdown-content\">\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">천안</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">공주</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">보령</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">아산</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">서산</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">논산</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">계룡</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">당진</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">금산</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">부여</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">서천</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">청양</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">홍성</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">예산</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">태안</div></a>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                  </div>\r\n");
      out.write("	                </td>\r\n");
      out.write("	\r\n");
      out.write("	                <!-- 충청북도 -->\r\n");
      out.write("	                <td>\r\n");
      out.write("	                  <div class=\"dropdown\">\r\n");
      out.write("	                    <button id=\"dropbtn4\" class=\"dropbtn\">\r\n");
      out.write("	                      <span id=\"dropbtn_content4\" class=\"dropbtn_content\"><p>충청북도</p></span>\r\n");
      out.write("	                      <span class=\"dropbtn_click\" style=\"font-family: Material Icons; font-size : 20px; color : #707070; float:right;\"\r\n");
      out.write("	                        onclick=\"dropdown4()\">arrow_drop_down</span>\r\n");
      out.write("	                    </button>\r\n");
      out.write("	                    <div id=\"dropdown-content4\" class=\"dropdown-content\">\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">청주</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">충주</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">제천</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">보은</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">옥천</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">영동</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">증평</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">진천</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">괴산</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">음성</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">단양</div></a>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                  </div>\r\n");
      out.write("	                </td>\r\n");
      out.write("	\r\n");
      out.write("	                <!-- 제주 -->\r\n");
      out.write("	                <td>제주</td>\r\n");
      out.write("	              </tr>\r\n");
      out.write("	\r\n");
      out.write("	              <!-- 마지막 행 -->\r\n");
      out.write("	              <tr>\r\n");
      out.write("	                <!-- 전라북도 -->\r\n");
      out.write("	                <td>\r\n");
      out.write("	                  <div class=\"dropdown\">\r\n");
      out.write("	                    <button id=\"dropbtn5\" class=\"dropbtn\">\r\n");
      out.write("	                      <span id=\"dropbtn_content5\" class=\"dropbtn_content\"><p>전라남도</p></span>\r\n");
      out.write("	                      <span class=\"dropbtn_click\" style=\"font-family: Material Icons; font-size : 20px; color : #707070; float:right;\"\r\n");
      out.write("	                        onclick=\"dropdown5()\">arrow_drop_down</span>\r\n");
      out.write("	                    </button>\r\n");
      out.write("	                    <div id=\"dropdown-content5\" class=\"dropdown-content\">\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">전주</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">익산</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">군산</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">정읍</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">남원</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">김제</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">무주</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">완주</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">부안</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">고창</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">임실</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">순창</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">진안</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">장수</div></a>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                  </div>\r\n");
      out.write("	                </td>\r\n");
      out.write("	\r\n");
      out.write("	                <!-- 전라남도 -->\r\n");
      out.write("	                <td>\r\n");
      out.write("	                  <div class=\"dropdown\">\r\n");
      out.write("	                    <button id=\"dropbtn6\" class=\"dropbtn\">\r\n");
      out.write("	                      <span id=\"dropbtn_content6\" class=\"dropbtn_content\"><p>전라북도</p></span>\r\n");
      out.write("	                      <span class=\"dropbtn_click\" style=\"font-family: Material Icons; font-size : 20px; color : #707070; float:right;\"\r\n");
      out.write("	                        onclick=\"dropdown6()\">arrow_drop_down</span>\r\n");
      out.write("	                    </button>\r\n");
      out.write("	                    <div id=\"dropdown-content6\" class=\"dropdown-content\">\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">목포</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">여수</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">순천</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">나주</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">광양</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">담양</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">곡성</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">구례</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">고흥</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">보성</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">화순</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">장흥</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">강진</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">해남</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">영암</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">무안</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">함평</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">영광</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">장성</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">완도</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">진도</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">신안</div></a>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                  </div>\r\n");
      out.write("	                </td>\r\n");
      out.write("	\r\n");
      out.write("	                <!-- 광주 -->\r\n");
      out.write("	                <td>광주</td>\r\n");
      out.write("	\r\n");
      out.write("	                <!-- 울산 -->\r\n");
      out.write("	                <td>울산</td>\r\n");
      out.write("	\r\n");
      out.write("	                <!-- 경상남도 -->\r\n");
      out.write("	                <td>\r\n");
      out.write("	                  <div class=\"dropdown\">\r\n");
      out.write("	                    <button id=\"dropbtn7\" class=\"dropbtn\">\r\n");
      out.write("	                      <span id=\"dropbtn_content7\" class=\"dropbtn_content\"><p>경상남도</p></span>\r\n");
      out.write("	                      <span class=\"dropbtn_click\" style=\"font-family: Material Icons; font-size : 20px; color : #707070; float:right;\"\r\n");
      out.write("	                        onclick=\"dropdown7()\">arrow_drop_down</span>\r\n");
      out.write("	                    </button>\r\n");
      out.write("	                    <div id=\"dropdown-content7\" class=\"dropdown-content\">\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">창원</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">김해</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">양산</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">진주</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">거제</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">통영</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">사천</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">밀양</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">함안</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">거창</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">창녕</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">고산</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">창년</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">하동</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">합천</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">남해</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">함양</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">산청</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">의령</div></a>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                  </div>\r\n");
      out.write("	                </td>\r\n");
      out.write("	\r\n");
      out.write("	                <!-- 경상북도 -->\r\n");
      out.write("	                <td>\r\n");
      out.write("	                  <div class=\"dropdown\">\r\n");
      out.write("	                    <button id=\"dropbtn8\" class=\"dropbtn\">\r\n");
      out.write("	                      <span id=\"dropbtn_content8\" class=\"dropbtn_content\"><p>경상북도</p></span>\r\n");
      out.write("	                      <span class=\"dropbtn_click\" style=\"font-family: Material Icons; font-size : 20px; color : #707070; float:right;\"\r\n");
      out.write("	                        onclick=\"dropdown8()\">arrow_drop_down</span>\r\n");
      out.write("	                    </button>\r\n");
      out.write("	                    <div id=\"dropdown-content8\" class=\"dropdown-content\">\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">포항</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">경주</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">김천</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">안동</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">구미</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">영주</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">영천</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">상주</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">문경</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">경신</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">의성</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">청송</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">영양</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">영덕</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">청도</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">고령</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">성주</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">칠곡</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">예천</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">봉화</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">울진</div></a>\r\n");
      out.write("	                      <a href=\"#\"><div class=\"city2\">울릉</div></a>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                  </div>\r\n");
      out.write("	                </td>\r\n");
      out.write("	\r\n");
      out.write("	                <!-- 부산 -->\r\n");
      out.write("	                <td>부산</td>\r\n");
      out.write("	\r\n");
      out.write("	                <!-- 대구 -->\r\n");
      out.write("	                <td>대구</td>\r\n");
      out.write("	              </tr>\r\n");
      out.write("	            </tbody>\r\n");
      out.write("	          </table>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- 요즘 많이 찾는 지역 -> 상세보기 이동 영역 -->\r\n");
      out.write("      <div id=\"visitCity\">\r\n");
      out.write("        <p>요즘 많이 찾는 지역</p>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"visitCity_image\"> \r\n");
      out.write("          <div class=\"image_datail\">\r\n");
      out.write("            <a href=\"http://localhost:8080/travel/gangneung.jsp\"><img src=\"images/gangneung.png\" alt=\"강릉\">\r\n");
      out.write("            <p>강릉<br>상세보기</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"image_datail\">\r\n");
      out.write("            <a href=\"http://localhost:8080/travel/seoul.jsp\"><img src=\"images/seoul.png\" alt=\"서울\">\r\n");
      out.write("            <p>서울<br>상세보기</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"image_datail\">\r\n");
      out.write("            <a href=\"http://localhost:8080/travel/jeju.jsp\"><img src=\"images/jeju.png\" alt=\"제주\">\r\n");
      out.write("            <p>제주<br>상세보기</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"image_datail\">\r\n");
      out.write("            <a href=\"http://localhost:8080/travel/busan.jsp\"><img src=\"images/busan.png\" alt=\"부산\" class=\"image4\">\r\n");
      out.write("            <p>부산<br>상세보기</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- 요즘 인기 있는 공간 : 롤링배너 -->\r\n");
      out.write("      <div id=\"popularCity\">\r\n");
      out.write("        <p>요즘 인기 있는 공간</p>\r\n");
      out.write("        <!-- 스토리 형식 : 10개로 고정 -->\r\n");
      out.write("        <!-- 사진 클릭 시, 여행 후기 카데고리로 이동 후 내용 확인 가능 -->\r\n");
      out.write("        <div class=\"rollingbanner\">\r\n");
      out.write("          <div class=\"slide\"> <!-- 배너 표시 영역 -->\r\n");
      out.write("            <div class=\"roller\"> <!-- 원본 배너 -->\r\n");
      out.write("              <ul> <!-- 배너 데이터 -->\r\n");
      out.write("                <li class=\"slide_image\">\r\n");
      out.write("                  <a href=\"#\"><img id=\"image1\" src=\"images/pohang-homigot.png\" alt=\"호미곶\"></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"slide_image\">\r\n");
      out.write("                  <a href=\"#\"><img id=\"image2\" src=\"images/woman-flower.jpg\" alt=\"사진찍는여성\"></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"slide_image\">\r\n");
      out.write("                  <a href=\"#\"><img id=\"image3\" src=\"images/lotte-tower.jpg\" alt=\"롯데타워\"></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"slide_image\">\r\n");
      out.write("                  <a href=\"#\"><img id=\"image4\" src=\"images/Daegwallyeong.jpg\" alt=\"대관령\"></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"slide_image\">\r\n");
      out.write("                  <a href=\"#\"><img id=\"image5\" src=\"images/gyeongbokgung-palace.jpg\" alt=\"경복궁\"></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"slide_image\">\r\n");
      out.write("                  <a href=\"#\"><img id=\"image6\" src=\"images/damyang-metasequoia.jpg\" alt=\"담양의 메타세콰이어길\"></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"slide_image\">\r\n");
      out.write("                  <a href=\"#\"><img id=\"image7\" src=\"images/busan-train.jpg\" alt=\"부산레일기차\"></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"slide_image\">\r\n");
      out.write("                  <a href=\"#\"><img id=\"image8\" src=\"images/choenjiyeon-falls.jpg\" alt=\"천지연폭포\"></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"slide_image\">\r\n");
      out.write("                  <a href=\"#\"><img id=\"image9\" src=\"images/incheon-bridge.jpg\" alt=\"인천대교\"></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"slide_image\">\r\n");
      out.write("                  <a href=\"#\"><img id=\"image10\" src=\"images/gyeongju.jpg\" alt=\"경주\"></a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div> \r\n");
      out.write("\r\n");
      out.write("      <!-- 다가오는 행사 및 전시회 -->\r\n");
      out.write("      <div id=\"comingup\">\r\n");
      out.write("        <span class=\"comingup-title\"><p>다가오는 행사 및 전시회</p></span>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"comingupbox\">\r\n");
      out.write("          <div id=\"calendarbox\">\r\n");
      out.write("            <div class=\"calendar-wrap\">\r\n");
      out.write("              <h2 class=\"month-year\">DEC.</h2>\r\n");
      out.write("              <h2 class=\"month-year2\">DECEMBER</h2>\r\n");
      out.write("            \r\n");
      out.write("              <table class=\"calendar\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <th class=\"day-title\" scope=\"col\">Sun</th>\r\n");
      out.write("                    <th class=\"day-title\" scope=\"col\">Mon</th>\r\n");
      out.write("                    <th class=\"day-title\" scope=\"col\">Tue</th>\r\n");
      out.write("                    <th class=\"day-title\" scope=\"col\">Wed</th>\r\n");
      out.write("                    <th class=\"day-title\" scope=\"col\">Thu</th>\r\n");
      out.write("                    <th class=\"day-title\" scope=\"col\">Fri</th>\r\n");
      out.write("                    <th class=\"day-title\" scope=\"col\">Sat</th>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                  <tr class=\"week\">\r\n");
      out.write("                    <td class=\"day prev-mon\" tabindex=\"0\"><span class=\"day-number\">27</span></td>\r\n");
      out.write("                    <td class=\"day prev-mon\" tabindex=\"0\"><span class=\"day-number\">28</span></td>\r\n");
      out.write("                    <td class=\"day prev-mon\" tabindex=\"0\"><span class=\"day-number\">29</span></td>\r\n");
      out.write("                    <td class=\"day prev-mon\" tabindex=\"0\"><span class=\"day-number\">30</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">1</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">2</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">3</span></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr class=\"week\">\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">4</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">5</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">6</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">7</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">8</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">9</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">10</span></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr class=\"week\">\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">11</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">12</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">13</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">14</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">15</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">16</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">17</span></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr class=\"week\">\r\n");
      out.write("                    <td class=\"day today\" tabindex=\"0\"><span class=\"day-number\">18</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">19</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">20</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">21</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">22</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">23</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">24</span></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr class=\"week\">\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">25</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">26</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">27</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">28</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">29</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">30</span></td>\r\n");
      out.write("                    <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">31</span></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("              </table>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("          <div id=\"eventlist\">\r\n");
      out.write("            <div class=\"eventlist-wrap\">\r\n");
      out.write("\r\n");
      out.write("              <!-- 날짜 미선택 시, 보이는 화면 -->\r\n");
      out.write("              <div class=\"slider_daypickno\">\r\n");
      out.write("                <span class=\"daypick\"><p>원하는 날짜를 클릭해주세요.</p></span>\r\n");
      out.write("                <div class=\"slider_btn\">\r\n");
      out.write("                  <button class=\"prev\"><i id=\"prev\" class=\"fa-solid fa-chevron-left\" style=\"color: #444444;\"></i></button>\r\n");
      out.write("                  <button class=\"next\"><i id=\"next\" class=\"fa-solid fa-chevron-right\" style=\"color: #444444;\"></i></button>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("              <!-- 날짜 선택 시, 보이는 화면 -->\r\n");
      out.write("              <!-- 버튼을 누르면 이전,다음 행사/전시회 슬라이드로 확인 -->\r\n");
      out.write("              <div class=\"slider_wrap\">\r\n");
      out.write("                <div class=\"slider_img\">\r\n");
      out.write("                  <div class=\"slider_inner\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"card mb-3\" style=\"max-width: 600px;\">\r\n");
      out.write("                      <div class=\"row g-0\">\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                          <img src=\"images/festival/light.jpeg\" class=\"img-fluid rounded-start\" alt=\"불빛동화축제\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-8\">\r\n");
      out.write("                          <div class=\"card-body\">\r\n");
      out.write("                            <h5 class=\"card-title\">허브아일랜드 불빛동화축제</h5>\r\n");
      out.write("                            <hr>\r\n");
      out.write("                            <p class=\"card-text\">기간 : 2023.02.01 (수) ~ 2023.12.31 (일)</p>\r\n");
      out.write("                            <p class=\"card-text\">시간 : 10:00 ~ 21:00</p>\r\n");
      out.write("                            <p class=\"card-text\">장소 : 허브아일랜드</p>\r\n");
      out.write("                            <p class=\"card-text\">요금 : 유료</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("      \r\n");
      out.write("                    <div class=\"card mb-3\" style=\"max-width: 600px;\">\r\n");
      out.write("                      <div class=\"row g-0\">\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                          <img src=\"images/festival/haeundae.jpeg\" class=\"img-fluid rounded-start\" alt=\"해운대빛축제\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-8\">\r\n");
      out.write("                          <div class=\"card-body\">\r\n");
      out.write("                            <h5 class=\"card-title\">해운대 빛축제</h5>\r\n");
      out.write("                            <hr>\r\n");
      out.write("                            <p class=\"card-text\">기간 : 2023.12.02 (토) ~ 2024.01.31 (수)</p>\r\n");
      out.write("                            <p class=\"card-text\">장소 : 해운대해수욕장, 해운대광장, 해운대시장, 온천길 일원</p>\r\n");
      out.write("                            <p class=\"card-text\">요금 : 무료</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("      \r\n");
      out.write("                    <div class=\"card mb-3\" style=\"max-width: 600px;\">\r\n");
      out.write("                      <div class=\"row g-0\">\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                          <img src=\"images/festival/gwanghwamun.jpeg\" class=\"img-fluid rounded-start\" alt=\"광화문광장마켓\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-8\">\r\n");
      out.write("                          <div class=\"card-body\">\r\n");
      out.write("                            <h5 class=\"card-title\">광화문광장 마켓</h5>\r\n");
      out.write("                            <hr>\r\n");
      out.write("                            <p class=\"card-text\">기간 : 2023.12.15 (금) ~ 2024.01.21 (일)</p>\r\n");
      out.write("                            <p class=\"card-text\">시간 : 18:00 ~ 22:00</p>\r\n");
      out.write("                            <p class=\"card-text\">장소 : 광화문광장, 세종로공원</p>\r\n");
      out.write("                            <p class=\"card-text\">요금 : 무료</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("      \r\n");
      out.write("                    <div class=\"card mb-3\" style=\"max-width: 600px;\">\r\n");
      out.write("                      <div class=\"row g-0\">\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                          <img src=\"images/festival/mansucheon.jpeg\" class=\"img-fluid rounded-start\" alt=\"만수천빛의거리\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-8\">\r\n");
      out.write("                          <div class=\"card-body\">\r\n");
      out.write("                            <h5 class=\"card-title\">만수천 빛의거리</h5>\r\n");
      out.write("                            <hr>\r\n");
      out.write("                            <p class=\"card-text\">기간 : 2023.12.08 (금) ~ 2024.01.31 (일)</p>\r\n");
      out.write("                            <p class=\"card-text\">시간 : 17:00 ~ 22:00</p>\r\n");
      out.write("                            <p class=\"card-text\">장소 : 만수복개천 공영주차장 일원</p>\r\n");
      out.write("                            <p class=\"card-text\">요금 : 무료</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("      \r\n");
      out.write("                    <div class=\"card mb-3\" style=\"max-width: 600px;\">\r\n");
      out.write("                      <div class=\"row g-0\">\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                          <img src=\"images/festival/ganjeolgot.jpeg\" class=\"img-fluid rounded-start\" alt=\"간절곶 해맞이\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-8\">\r\n");
      out.write("                          <div class=\"card-body\">\r\n");
      out.write("                            <h5 class=\"card-title\">간절곶 해맞이</h5>\r\n");
      out.write("                            <hr>\r\n");
      out.write("                            <p class=\"card-text\">기간 : 2023.12.31 (일) ~ 2024.01.01 (월)</p>\r\n");
      out.write("                            <p class=\"card-text\">장소 : 울주군 간절곶 공원</p>\r\n");
      out.write("                            <p class=\"card-text\">요금 : 무료</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("      \r\n");
      out.write("                    <div class=\"card mb-3\" style=\"max-width: 600px;\">\r\n");
      out.write("                      <div class=\"row g-0\">\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                          <img src=\"images/festival/snow.jpeg\" class=\"img-fluid rounded-start\" alt=\"스노우 페스티벌\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-8\">\r\n");
      out.write("                          <div class=\"card-body\">\r\n");
      out.write("                            <h5 class=\"card-title\">씨파크 스노우 페스티벌</h5>\r\n");
      out.write("                            <hr>\r\n");
      out.write("                            <p class=\"card-text\">기간 : 2023.12.23 (토) ~ 2024.02.28 (수)</p>\r\n");
      out.write("                            <p class=\"card-text\">시간 : 10:00 ~ 17:00</p>\r\n");
      out.write("                            <p class=\"card-text\">장소 : 합천 씨파크, 카페모토라드 합천</p>\r\n");
      out.write("                            <p class=\"card-text\">요금 : 유료</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("      \r\n");
      out.write("                    <div class=\"card mb-3\" style=\"max-width: 600px;\">\r\n");
      out.write("                      <div class=\"row g-0\">\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                          <img src=\"images/festival/cheonggaechun.jpeg\" class=\"img-fluid rounded-start\" alt=\"겨울, 청계천의 빛\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-8\">\r\n");
      out.write("                          <div class=\"card-body\">\r\n");
      out.write("                            <h5 class=\"card-title\">겨울, 청계천의 빛</h5>\r\n");
      out.write("                            <hr>\r\n");
      out.write("                            <p class=\"card-text\">기간 : 2023.12.15 (금) ~ 2023.12.31 (일)</p>\r\n");
      out.write("                            <p class=\"card-text\">장소 : 청계광장</p>\r\n");
      out.write("                            <p class=\"card-text\">요금 : 무료</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                  </div> <!-- slider_inner -->\r\n");
      out.write("                </div> <!-- slider_img -->\r\n");
      out.write("              </div> <!-- slider_wrap -->\r\n");
      out.write("\r\n");
      out.write("            </div> <!-- eventlist-wrap-->\r\n");
      out.write("          </div> <!-- eventlist -->\r\n");
      out.write("        </div> <!-- comingupbox -->\r\n");
      out.write("        \r\n");
      out.write("      </div> <!-- comingup -->\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"../resources/js/main.js\"></script>\r\n");
      out.write("    <script src=\"js/in_main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </section> <!-- main_container -->\r\n");
      out.write("  \r\n");
      out.write("  <!-- footer 부분 -->\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
