/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2024-01-02 08:30:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.travel;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class out_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>해외 여행 | 메인</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/out_main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/style.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/aa24b12773.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- header -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<section id=\"main_container\">\r\n");
      out.write("	    <!-- body 부분 -->\r\n");
      out.write("	    <section>\r\n");
      out.write("	       <!-- 국가/도시 검색 창 영역 -->\r\n");
      out.write("      <div id=\"mainPicture\">\r\n");
      out.write("        <img src=\"images/out_main/swiss-peak.jpg\" alt=\"메인 화면\">\r\n");
      out.write("        <div class=\"searchTravel\">\r\n");
      out.write("          <p>어디로 여행가시나요?</p>\r\n");
      out.write("          <div class=\"searchWord\">\r\n");
      out.write("            <label>\r\n");
      out.write("              <input type=\"text\" placeholder=\" 국가명, 도시명으로 검색하세요. (추천 도시 : 홍콩, 뉴욕, 제주도)\" size=\"65%\">\r\n");
      out.write("              <button type=\"button\"><i class=\"fa-solid fa-magnifying-glass fa-lg\" style=\"color: #606060;\"></i></button>\r\n");
      out.write("            </label>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- 대한민국 도시 선택 창 영역 -->\r\n");
      out.write("      <div id=\"searchCity\">\r\n");
      out.write("        <div class=\"searchCityBox\">\r\n");
      out.write("          <p>해외 여행지</p>\r\n");
      out.write("          <table>\r\n");
      out.write("            <tbody>\r\n");
      out.write("              <!-- 첫번째 행 -->\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td>주요 나라</td>\r\n");
      out.write("                <td>일본</td>\r\n");
      out.write("                <td>중국</td>\r\n");
      out.write("                <td>태국</td>\r\n");
      out.write("                <td>대만</td>\r\n");
      out.write("                <td>영국</td>\r\n");
      out.write("                <td>한국</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              \r\n");
      out.write("              <!-- 두번째 행 -->\r\n");
      out.write("              <tr>\r\n");
      out.write("                <!-- 아시아 -->\r\n");
      out.write("                <td>\r\n");
      out.write("                  <div class=\"dropdown\">\r\n");
      out.write("                    <button id=\"dropbtn\" class=\"dropbtn\">\r\n");
      out.write("                      <span class=\"dropbtn_content\"><p>아시아</p></span>\r\n");
      out.write("                      <span class=\"dropbtn_click\" style=\"font-family: Material Icons; font-size : 20px; color : #707070; float:right;\"\r\n");
      out.write("                        onclick=\"dropdown()\">arrow_drop_down</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"dropdown-content\">\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">대한민국</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">북한</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">중국</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">마카오</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">홍콩</div></a>\r\n");
      out.write("                      <a href=\"http://localhost:8080/travel/japan.jsp\"><div class=\"city\">일본</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">대만</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">몽골</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">우즈베키스탄</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">카자흐스탄</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">키르기스스탄</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">타지키스탄</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">투르크메니스탄</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">동티모르</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">라오스</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">말레이시아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">미얀마</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">베트남</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">브루나이</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">싱가포르</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">인도네시아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">캄보디아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">태국</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">필리핀</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">레바논</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">바레인</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">사우디아라비아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">시리아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">아랍에미리트</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">오만</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">요르단</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">이라크</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">이란</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">이스라엘</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">카타르</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">팔레스타인</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">네팔</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">몰디브</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">방글라데시</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">스리랑카</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">아프가니스탄</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">인도</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city\">파키스탄</div></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </td>\r\n");
      out.write("\r\n");
      out.write("                <!-- 유럽 -->\r\n");
      out.write("                <td>\r\n");
      out.write("                  <div class=\"dropdown\">\r\n");
      out.write("                    <button id=\"dropbtn2\" class=\"dropbtn\">\r\n");
      out.write("                      <span id=\"dropbtn_content2\" class=\"dropbtn_content\"><p>유럽</p></span>\r\n");
      out.write("                      <span class=\"dropbtn_click\" style=\"font-family: Material Icons; font-size : 20px; color : #707070; float:right;\"\r\n");
      out.write("                        onclick=\"dropdown2()\">arrow_drop_down</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div id=\"dropdown-content2\" class=\"dropdown-content\">\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">독일</div></a>\r\n");
      out.write("                      <a href=\"http://localhost:8080/travel/unitedKingdom.jsp\"><div class=\"city2\">영국</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">프랑스</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">이탈리아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">러시아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">스페인</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">튀르키예</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">네덜란드</div></a>\r\n");
      out.write("                      <a href=\"http://localhost:8080/travel/switzerland.jsp\"><div class=\"city2\">스위스</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">폴란드</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">스웨덴</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">벨기에</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">오스트리아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">아일랜드</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">노르웨이</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">덴마크</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">핀란드</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">루마니아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">체코</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">포르투갈</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">그리스</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">헝가리</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">우크라이나</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">슬로바키아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">룩셈부르크</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">불가리아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">크로아티아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">라투아니아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">벨라루스</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">세르비아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">슬로베니아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">라트비아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">에스토니아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">키프로스</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">아이슬란드</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">보스니아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">알바니아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">몰타</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">북마케도니아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">몰도바</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">모나코</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">리히텐슈타인</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">몬테네그로</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">안도라</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">산마리노</div></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </td>\r\n");
      out.write("\r\n");
      out.write("                <!-- 북아메리카 -->\r\n");
      out.write("                <td>\r\n");
      out.write("                  <div class=\"dropdown\">\r\n");
      out.write("                    <button id=\"dropbtn3\" class=\"dropbtn\">\r\n");
      out.write("                      <span id=\"dropbtn_content3\" class=\"dropbtn_content\"><p>북아메리카</p></span>\r\n");
      out.write("                      <span class=\"dropbtn_click\" style=\"font-family: Material Icons; font-size : 20px; color : #707070; float:right;\"\r\n");
      out.write("                        onclick=\"dropdown3()\">arrow_drop_down</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div id=\"dropdown-content3\" class=\"dropdown-content\">\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">캐나다</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">미국</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">멕시코</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">벨리즈</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">과테말라</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">엘살바도르</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">온두라스</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">니카라과</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">코스타리카</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">파나마</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">바하마</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">쿠바</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">자메이카</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">아이티</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">도미니카</div></a>    \r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </td>\r\n");
      out.write("\r\n");
      out.write("                <!-- 남아메리카 -->\r\n");
      out.write("                <td>\r\n");
      out.write("                  <div class=\"dropdown\">\r\n");
      out.write("                    <button id=\"dropbtn4\" class=\"dropbtn\">\r\n");
      out.write("                      <span id=\"dropbtn_content4\" class=\"dropbtn_content\"><p>남아메리카</p></span>\r\n");
      out.write("                      <span class=\"dropbtn_click\" style=\"font-family: Material Icons; font-size : 20px; color : #707070; float:right;\"\r\n");
      out.write("                        onclick=\"dropdown4()\">arrow_drop_down</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div id=\"dropdown-content4\" class=\"dropdown-content\">\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">가이아나</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">베네수엘라</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">볼리비아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">브라질</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">수리남</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">아르헨티나</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">에콰도르</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">우루과이</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">칠레</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">콜롬비아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">파라과이</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">페루</div></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </td>\r\n");
      out.write("\r\n");
      out.write("                <!-- 아프리카 -->\r\n");
      out.write("                <td>\r\n");
      out.write("                  <div class=\"dropdown\">\r\n");
      out.write("                    <button id=\"dropbtn5\" class=\"dropbtn\">\r\n");
      out.write("                      <span id=\"dropbtn_content5\" class=\"dropbtn_content\"><p>아프리카</p></span>\r\n");
      out.write("                      <span class=\"dropbtn_click\" style=\"font-family: Material Icons; font-size : 20px; color : #707070; float:right;\"\r\n");
      out.write("                        onclick=\"dropdown5()\">arrow_drop_down</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div id=\"dropdown-content5\" class=\"dropdown-content\">\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">모로코</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">알제리</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">튀니지</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">리비아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">이집트</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">소말리아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">에티오피아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">남수단</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">우간다</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">르완도</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">케냐</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">탄자니아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">잠비아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">짐바브웨</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">마다가스카르</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">남아공</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">콩고</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">가봉</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">적도기니</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">카메룬</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">나이지리아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">가나</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">토고</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">코트니부아르</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">세네갈</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">말리</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">기니</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">감비아</div></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </td>\r\n");
      out.write("                \r\n");
      out.write("                <!-- 오스트레일리아 -->\r\n");
      out.write("                <td>\r\n");
      out.write("                  <div class=\"dropdown\">\r\n");
      out.write("                    <button id=\"dropbtn6\" class=\"dropbtn\">\r\n");
      out.write("                      <span id=\"dropbtn_content6\" class=\"dropbtn_content\"><p>오세아니아</p></span>\r\n");
      out.write("                      <span class=\"dropbtn_click\" style=\"font-family: Material Icons; font-size : 20px; color : #707070; float:right;\"\r\n");
      out.write("                        onclick=\"dropdown6()\">arrow_drop_down</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div id=\"dropdown-content6\" class=\"dropdown-content\">\r\n");
      out.write("                      <a href=\"http://localhost:8080/travel/australia.jsp\"><div class=\"city2\">호주</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">뉴질랜드</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">멜라네시아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">미크로네시아</div></a>\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">폴리네시아</div></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </td>\r\n");
      out.write("                \r\n");
      out.write("                <!-- 남극 -->\r\n");
      out.write("                <td>\r\n");
      out.write("                  <div class=\"dropdown\">\r\n");
      out.write("                    <button id=\"dropbtn7\" class=\"dropbtn\">\r\n");
      out.write("                      <span id=\"dropbtn_content7\" class=\"dropbtn_content\"><p>남극</p></span>\r\n");
      out.write("                      <span class=\"dropbtn_click\" style=\"font-family: Material Icons; font-size : 20px; color : #707070; float:right;\"\r\n");
      out.write("                        onclick=\"dropdown7()\">arrow_drop_down</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div id=\"dropdown-content7\" class=\"dropdown-content\">\r\n");
      out.write("                      <a href=\"#\"><div class=\"city2\">남극기지</div></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </tbody>\r\n");
      out.write("          </table>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 요즘 많이 찾는 지역 -> 상세보기 이동 영역 -->\r\n");
      out.write("    <div id=\"visitCity\">\r\n");
      out.write("      <p>요즘 많이 찾는 지역</p>\r\n");
      out.write("      \r\n");
      out.write("      <div id=\"visitCity_image\"> \r\n");
      out.write("        <div class=\"image_datail\">\r\n");
      out.write("          <a href=\"http://localhost:8080/travel/unitedKingdom.jsp\"><img src=\"images/out_main/tower-bridge.png\" alt=\"영국\">\r\n");
      out.write("          <p>영국<br>상세보기</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"image_datail\">\r\n");
      out.write("          <a href=\"http://localhost:8080/travel/switzerland.jsp\"><img src=\"images/out_main/swiss-mountain.png\" alt=\"스위스\">\r\n");
      out.write("          <p>스위스<br>상세보기</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"image_datail\">\r\n");
      out.write("          <a href=\"http://localhost:8080/travel/japan.jsp\"><img src=\"images/out_main/osaka-castle.png\" alt=\"일본\">\r\n");
      out.write("          <p>일본<br>상세보기</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"image_datail\">\r\n");
      out.write("          <a href=\"http://localhost:8080/travel/australia.jsp\"><img src=\"images/out_main/austraila-opera.png\" alt=\"호주\" class=\"image4\">\r\n");
      out.write("          <p>호주<br>상세보기</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 요즘 인기 있는 공간 : 롤링배너 -->\r\n");
      out.write("    <div id=\"popularCity\">\r\n");
      out.write("      <p>요즘 인기 있는 공간</p>\r\n");
      out.write("      <!-- 스토리 형식 : 10개로 고정 -->\r\n");
      out.write("      <!-- 사진 클릭 시, 여행 후기 카데고리로 이동 후 내용 확인 가능 -->\r\n");
      out.write("      <div class=\"rollingbanner\">\r\n");
      out.write("        <div class=\"slide\"> <!-- 배너 표시 영역 -->\r\n");
      out.write("          <div class=\"roller\"> <!-- 원본 배너 -->\r\n");
      out.write("            <ul> <!-- 배너 데이터 -->\r\n");
      out.write("              <li class=\"slide_image\">\r\n");
      out.write("                <a href=\"#\"><img id=\"image1\" src=\"images/out_main/buildings.jpg\" alt=\"중국\"></a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"slide_image\">\r\n");
      out.write("                <a href=\"http://localhost:8080/travel/switzerland.jsp\"><img id=\"image2\" src=\"images/out_main/mountains.jpg\" alt=\"스위스\"></a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"slide_image\">\r\n");
      out.write("                <a href=\"http://localhost:8080/travel/unitedKingdom.jsp\"><img id=\"image3\" src=\"images/out_main/road.jpg\" alt=\"영국\"></a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"slide_image\">\r\n");
      out.write("                <a href=\"#\"><img id=\"image4\" src=\"images/out_main/trees.jpg\" alt=\"캐나다\"></a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"slide_image\">\r\n");
      out.write("                <a href=\"#\"><img id=\"image5\" src=\"images/out_main/venice.jpg\" alt=\"이탈리아\"></a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"slide_image\">\r\n");
      out.write("                <a href=\"#\"><img id=\"image6\" src=\"images/out_main/cathedral.jpg\" alt=\"유럽1\"></a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"slide_image\">\r\n");
      out.write("                <a href=\"#\"><img id=\"image7\" src=\"images/out_main/restaurant.jpg\" alt=\"유럽2\"></a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"slide_image\">\r\n");
      out.write("                <a href=\"#\"><img id=\"image8\" src=\"images/out_main/eiffel.jpg\" alt=\"유럽3\"></a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"slide_image\">\r\n");
      out.write("                <a href=\"#\"><img id=\"image9\" src=\"images/out_main/prague.jpg\" alt=\"유럽4\"></a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"slide_image\">\r\n");
      out.write("                <a href=\"#\"><img id=\"image10\" src=\"images/out_main/buildings-america.jpg\" alt=\"미국\"></a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div> \r\n");
      out.write("\r\n");
      out.write("    <!-- 다가오는 행사 및 전시회 -->\r\n");
      out.write("    <div id=\"comingup\">\r\n");
      out.write("      <span class=\"comingup-title\"><p>다가오는 행사 및 전시회</p></span>\r\n");
      out.write("\r\n");
      out.write("      <div id=\"comingupbox\">\r\n");
      out.write("        <div id=\"calendarbox\">\r\n");
      out.write("          <div class=\"calendar-wrap\">\r\n");
      out.write("            <h2 class=\"month-year\">DEC.</h2>\r\n");
      out.write("            <h2 class=\"month-year2\">DECEMBER</h2>\r\n");
      out.write("          \r\n");
      out.write("            <table class=\"calendar\">\r\n");
      out.write("              <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th class=\"day-title\" scope=\"col\">Sun</th>\r\n");
      out.write("                  <th class=\"day-title\" scope=\"col\">Mon</th>\r\n");
      out.write("                  <th class=\"day-title\" scope=\"col\">Tue</th>\r\n");
      out.write("                  <th class=\"day-title\" scope=\"col\">Wed</th>\r\n");
      out.write("                  <th class=\"day-title\" scope=\"col\">Thu</th>\r\n");
      out.write("                  <th class=\"day-title\" scope=\"col\">Fri</th>\r\n");
      out.write("                  <th class=\"day-title\" scope=\"col\">Sat</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </thead>\r\n");
      out.write("              <tbody>\r\n");
      out.write("                <tr class=\"week\">\r\n");
      out.write("                  <td class=\"day prev-mon\" tabindex=\"0\"><span class=\"day-number\">27</span></td>\r\n");
      out.write("                  <td class=\"day prev-mon\" tabindex=\"0\"><span class=\"day-number\">28</span></td>\r\n");
      out.write("                  <td class=\"day prev-mon\" tabindex=\"0\"><span class=\"day-number\">29</span></td>\r\n");
      out.write("                  <td class=\"day prev-mon\" tabindex=\"0\"><span class=\"day-number\">30</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">1</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">2</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">3</span></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"week\">\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">4</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">5</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">6</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">7</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">8</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">9</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">10</span></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"week\">\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">11</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">12</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">13</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">14</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">15</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">16</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">17</span></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"week\">\r\n");
      out.write("                  <td class=\"day today\" tabindex=\"0\"><span class=\"day-number\">18</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">19</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">20</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">21</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">22</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">23</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">24</span></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr class=\"week\">\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">25</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">26</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">27</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">28</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">29</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">30</span></td>\r\n");
      out.write("                  <td class=\"day\" tabindex=\"0\"><span class=\"day-number\">31</span></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div id=\"eventlist\">\r\n");
      out.write("          <div class=\"eventlist-wrap\">\r\n");
      out.write("\r\n");
      out.write("            <!-- 날짜 미선택 시, 보이는 화면 -->\r\n");
      out.write("            <div class=\"slider_daypickno\">\r\n");
      out.write("              <span class=\"daypick\"><p>원하는 날짜를 클릭해주세요.</p></span>\r\n");
      out.write("              <div class=\"slider_btn\">\r\n");
      out.write("                <button class=\"prev\"><i id=\"prev\" class=\"fa-solid fa-chevron-left\" style=\"color: #444444;\"></i></button>\r\n");
      out.write("                <button class=\"next\"><i id=\"next\" class=\"fa-solid fa-chevron-right\" style=\"color: #444444;\"></i></button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- 날짜 선택 시, 보이는 화면 -->\r\n");
      out.write("            <!-- 버튼을 누르면 이전,다음 행사/전시회 슬라이드로 확인 -->\r\n");
      out.write("            <div class=\"slider_wrap\">\r\n");
      out.write("              <div class=\"slider_img\">\r\n");
      out.write("                <div class=\"slider_inner\">\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"card mb-3\" style=\"max-width: 600px;\">\r\n");
      out.write("                    <div class=\"row g-0\">\r\n");
      out.write("                      <div class=\"col-md-4\">\r\n");
      out.write("                        <img src=\"images/festival/canival.jpg\" class=\"img-fluid rounded-start\" alt=\"해운대빛축제\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col-md-8\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                          <h5 class=\"card-title\">쾰른 카니발</h5>\r\n");
      out.write("                          <hr>\r\n");
      out.write("                          <p class=\"card-text\">기간(현지기준) : 2023.11.11 ~ 2023.02.15</p>\r\n");
      out.write("                          <p class=\"card-text\">장소 : 독일 노르트라인베스트팔렌주 쾰른</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("    \r\n");
      out.write("                  <div class=\"card mb-3\" style=\"max-width: 600px;\">\r\n");
      out.write("                    <div class=\"row g-0\">\r\n");
      out.write("                      <div class=\"col-md-4\">\r\n");
      out.write("                        <img src=\"images/festival/lucia.png\" class=\"img-fluid rounded-start\" alt=\"광화문광장마켓\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col-md-8\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                          <h5 class=\"card-title\">성 루시아 축일</h5>\r\n");
      out.write("                          <hr>\r\n");
      out.write("                          <p class=\"card-text\">기간(현지기준) : 2023.12.13</p>\r\n");
      out.write("                          <p class=\"card-text\">장소 : 스웨덴 전역</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("    \r\n");
      out.write("                  <div class=\"card mb-3\" style=\"max-width: 600px;\">\r\n");
      out.write("                    <div class=\"row g-0\">\r\n");
      out.write("                      <div class=\"col-md-4\">\r\n");
      out.write("                        <img src=\"images/festival/dubai.jpg\" class=\"img-fluid rounded-start\" alt=\"만수천빛의거리\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col-md-8\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                          <h5 class=\"card-title\">두바이 쇼핑 페스티벌</h5>\r\n");
      out.write("                          <hr>\r\n");
      out.write("                          <p class=\"card-text\">기간(현지기준) : 2023.12.08 ~ 2024.01.14</p>\r\n");
      out.write("                          <p class=\"card-text\">장소 : 아랍에미리트 두바이</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("    \r\n");
      out.write("                </div> <!-- slider_inner -->\r\n");
      out.write("              </div> <!-- slider_img -->\r\n");
      out.write("            </div> <!-- slider_wrap -->\r\n");
      out.write("\r\n");
      out.write("          </div> <!-- eventlist-wrap-->\r\n");
      out.write("        </div> <!-- eventlist -->\r\n");
      out.write("      </div> <!-- comingupbox -->\r\n");
      out.write("      \r\n");
      out.write("    </div> <!-- comingup -->\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"../resources/js/main.js\"></script>\r\n");
      out.write("    <script src=\"js/in_main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </section> <!-- main_container -->\r\n");
      out.write("  \r\n");
      out.write("  <!-- footer 부분 -->\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
